config/routes.rb
Rails.application.routes.draw do
  root 'application#index'
  get 'users/login', to: 'users#login'



  # TETING Process... ***************
  get 'home/show'
  get 'home/profile_page'

  # devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations' }
  # ***************

  # get 'users/login', to: 'projects#created'
 
  
  devise_for :users,
         path: 'devise'
        #path: 'project'


  devise_scope :user do
    get 'devise/sign_out', to: 'devise/sessions#destroy'
    get 'destroy_user/:id' => "users#destroy_user"
    get 'remove_from_admin/:id' => "users#remove_from_admin"
    get 'add_admin/:id' => "users#add_admin", as: 'add_admin_form'
    post 'add_admin/:id' => "users#add_admin", as: 'add_admin'
    # get 'sign_out', to: 'devise/sessions#destroy'
    get 'destroy_user/:id' => "users/sessions#destroy_user"
  

    # New ****************
    get 'user_admin', to: 'users/sessions#admin'
    delete 'destroy', to: 'users/sessions#destroy'
    get 'destroy_user/:id' => "users/sessions#destroy_user"
    get 'remove_from_admin/:id' => "users/sessions#remove_from_admin"
    get 'add_admin/:id' => "users/sessions#add_admin"

    get 'edit_user/:id' => "users#edit", as: 'edit_user_role'

      #******************


  end

  delete 'users/:id', to: 'users#destroy', as: 'delete_user'
  
  get 'users/add', to: 'users#adduser', as: 'add_user'
  post 'users/add', to: 'users#add_user', as: 'add_new_user'
  get 'projects/shared', to: 'projects#shared', as: 'shared_projects'
  get 'projects/created', to: 'projects#created', as: 'created_projects'
  post 'projects/new', to: 'projects#create', as: 'add_new_project'
  delete 'projects/:id', to: 'projects#destroy', as: 'destroy_project'
  get 'users', to: 'users#index', as: 'user_index'

  resources :projects
  resources :users
  
end

app/models/user.rb
class User < ApplicationRecord
  
  #added
  has_many :posts
  has_many :projects


  enum role: [:user, :admin]
  after_initialize :set_default_role, :if => :new_record?

  def set_default_role
    self.role ||= :user
  end

#has many relationship 
#user have many project

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
   
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    #  has_many :projects, dependent: :destroy
    #  validates :name, presence: true
    #  validates :email, presence: true
    #  validates :password, length: {minimum: 5}

     # GET method to get all users from database   
     def index   
      @users = User.all   
    end   
     
    # GET method for the new user form   
    def new     
      render layout: false
      @user = User.new 
    end   
     
    # POST method for processing form data   
    def create   
      @user = User.new(user_params)   
      if @user.save   
        flash[:notice] = 'Registered successfully!' 
        redirect_to users_login_url
        # redirect_to new_project_url  
      else   
        flash[:error] = 'Failed to create account!'   
        render :new   
      end   
    end 
    
    # GET method to get a user by id   
    def show   
      @user = User.find(params[:id])   
    end   
     


     # GET method for editing a user based on id   
    def edit   
      @user = User.find(params[:id])   
    end   
     
    # PUT method for updating in database a user based on id   
    def update   
      @user = User.find(params[:id])   
      if @user.update(user_params)   
        flash[:notice] = 'user updated!'   
        redirect_to user_index_path
     
      else   
        flash[:error] = 'Failed to edit user!'   
        render :edit   
      end   
    end   
     
    # DELETE method for deleting a user from database based on id   
    def destroy_user   
      @user = User.find(params[:id])   
      if @user.delete   
        flash[:notice] = 'user deleted!'   
        redirect_to root_path   
      else   
        flash[:error] = 'Failed to delete this user!'   
        render :destroy   
      end   
    end   

####################### # new testing code

def remove_from_admin
  if current_user.admin == true
    @user = User.find(params[:id])
    #@user.update(admin: false)
    @user.admin = false
    @user.save
    redirect_to home_show_path
  end
end


def add_admin
  if current_user.admin == true
    @user = User.find(params[:id])
    @user.admin = true
    @user.save
    redirect_to home_show_path
  end
end


def authorize_admin
  unless current_user.admin == true
    redirect_to root_path, alert: "You do not have permission to delete user"
  end
end

def destroy_user
  if current_user.admin == true
    @user = User.find(params[:id])
    @user.destroy
    redirect_to home_show_path, notice: "User has been deleted successfully"
  end
end


def destroy
  @user = User.find(params[:id])
  @user.destroy
  redirect_to root_path, notice: 'User successfully deleted.'
end




########################## tesging ###########################

    def login
      render layout: false
    end


    def sign_in
      render layout: false
    end

    # POST method for processing form data   
    def add_user   
      @user = User.new(user_params)   
      if @user.save   
        flash[:notice] = 'Registered successfully!' 
        redirect_to add_new_user_url    
      else   
        flash[:error] = 'Failed to create account!'   
        render :adduser   
      end   
    end 

    protected

    # validation of params   
    def user_params   
      params.permit(:name, :email, :password, :role)   
    end   

    
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/add_admin.html.erb
<div class="container-xl">
<div class="table-responsive">
    <div class="table-wrapper">
        <div class="table-title">
            <div class="row">
                <div class="col-sm-5">
                    <h2> <b>Update User </b></h2>
                </div>                    
            </div>
        </div>
        <div class="signup-form"> 
        <% if flash[:notice] %>  
          <div class="alert alert-success"><%= flash[:notice] %></div>  
        <% end %> 

        <% if flash[:error] %>  
          <div class="alert alert-warning"><%= flash[:error] %></div>  
        <% end %>  

        <%= form_with scope: @user, url: add_admin_path, method: :post, local: true do %>
        <p class="lead">Register a new user.</p>
        
        <div class="form-group">
          <div class="input-group">
            <input type="text" class="form-control" name="name" placeholder="Name" required="required">
          </div>
        </div>
        <div class="form-group">
          <div class="input-group">
            <input type="email" class="form-control" name="email" placeholder="Email Address" required="required">
          </div>
        </div>
      <div class="form-group">
        <div class="input-group">
          <input type="password" class="form-control" name="password" placeholder="Password" required="required">
        </div>
      </div>
      
      <div class="form-group">
      <select name="role" class="form-control">
        <option class="form-input">select role ..</option>
        <option class="form-input" value="user">User </option>
        <option class="form-input" value="admin"> Admin </option>
      </select>
      </div>

      <div class="form-group">
        <div class="input-group">
          <input type="password" class="form-control" name="confirm_password" placeholder="Confirm Password" required="required">
        </div>
      </div>     
                  
        <div class="form-group">
            <button type="submit" class="btn btn-primary btn-block btn-lg">Create</button>
        </div>
       <% end %> 
    </div>
</div>    
</div> 

app/views/users/adduser.html.erb
<div class="container-xl">
<div class="table-responsive">
    <div class="table-wrapper">
        <div class="table-title">
            <div class="row">
                <div class="col-sm-5">
                    <h2> <b>Add User </b></h2>
                </div>                    
            </div>
        </div>
        <div class="signup-form"> 
        <% if flash[:notice] %>  
          <div class="alert alert-success"><%= flash[:notice] %></div>  
        <% end %> 

        <% if flash[:error] %>  
          <div class="alert alert-warning"><%= flash[:error] %></div>  
        <% end %>  

        <%= form_with scope: @user, url: add_new_user_path, method: :post, local: true do %>
        <p class="lead">Register a new user.</p>
        
        <div class="form-group">
          <div class="input-group">
            <input type="text" class="form-control" name="name" placeholder="Name" required="required">
          </div>
        </div>
        <div class="form-group">
          <div class="input-group">
            <input type="email" class="form-control" name="email" placeholder="Email Address" required="required">
          </div>
        </div>
      <div class="form-group">
        <div class="input-group">
          <input type="password" class="form-control" name="password" placeholder="Password" required="required">
        </div>
      </div>
      
      <div class="form-group">
      <select name="role" class="form-control">
        <option class="form-input">select role ..</option>
        <option class="form-input" value="user">User </option>
        <option class="form-input" value="admin"> Admin </option>
      </select>
      </div>

      <div class="form-group">
        <div class="input-group">
          <input type="password" class="form-control" name="confirm_password" placeholder="Confirm Password" required="required">
        </div>
      </div>     
                  
        <div class="form-group">
            <button type="submit" class="btn btn-primary btn-block btn-lg">Create</button>
        </div>
       <% end %> 
    </div>
</div>    
</div> 

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

app/views/users/edit.html.erb
<%# <h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p> %>



<div class="container-xl">
<div class="table-responsive">
    <div class="table-wrapper">
        <div class="table-title">
            <div class="row">
                <div class="col-sm-5">
                    <h2> <b>Add User </b></h2>
                </div>                    
            </div>
        </div>
        <div class="signup-form"> 
        <% if flash[:notice] %>  
          <div class="alert alert-success"><%= flash[:notice] %></div>  
        <% end %> 

        <% if flash[:error] %>  
          <div class="alert alert-warning"><%= flash[:error] %></div>  
        <% end %>  

        <%= form_with scope: @user, url: user_path(@user), method: :patch, local: true do %>
        <p class="lead">Register a new user.</p>
        
        <div class="form-group">
          <div class="input-group">
            <input type="text" class="form-control" name="name" value="<%=@user.name%>"  required="required">
          </div>
        </div>
        <div class="form-group">
          <div class="input-group">
            <input type="email" class="form-control" name="email" value="<%=@user.email%>" required="required">
          </div>
        </div>

      <%# <div class="form-group">
        <div class="input-group">
          <input type="password" class="form-control" name="password" value="" required="required">
        </div>
      </div> %>
      
      <div class="form-group">
      <select name="role" class="form-control">
       <option class="form-input" value="<%@user.role %>"> <%=@user.role %> </option>
       
        <% if @user.role == 'user' %>
          <option class="form-input" value="admin"> Admin </option>  
        <% else %>
          <option class="form-input" value="user">User </option>   
        <% end %>

       
        
      </select>
      </div>

      <%# <div class="form-group">
        <div class="input-group">
          <input type="password" class="form-control" name="confirm_password" placeholder="Confirm Password" required="required">
        </div>
      </div>      %>
                  
        <div class="form-group">
            <button type="submit" class="btn btn-primary btn-block btn-lg">Create</button>
        </div>
       <% end %> 
    </div>
</div>    
</div> 

app/views/users/index.html.erb
<div class="container-xl">
<div class="table-responsive">
    <div class="table-wrapper">
        <div class="table-title">
            <div class="row">
                <div class="col-sm-5">
                    <h2><b>All Users</b></h2>
                </div>
                <div class="col-sm-7">
                    <a href="<%= add_user_path %>" class="btn btn-secondary"><i class="material-icons">&#xE147;</i> <span>Add New User</span></a>
                </div>
            </div>
        </div>
        <table class="table table-striped table-hover">
            <thead>
                <tr>
                    <th>#</th>
                    <th>Name</th>                       
                    <th>Email</th>
                    <th>Role</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
            <% @users.each do |user| %>
           
                <tr>
                    <td> <%= 1 %> </td>
                    <td> <%= user.name %> </td>
                    <td><%= user.email %></td>                        
                    <td><%= user.role %></td>
                    <td style="width: 140px">
                       
                        <%= link_to 'Edit', edit_user_role_path(user.id) %>
                        <a href="#" class="delete" title="Delete" data-toggle="tooltip"><i class="material-icons">&#xE872;</i></a>
                    </td>
                </tr>  
                <% end %>                  
            </tbody>
        </table>
        <div class="clearfix">
            <div class="hint-text">Showing <b>5</b> out of <b>25</b> entries</div>
            <ul class="pagination">
                <li class="page-item disabled"><a href="#">Previous</a></li>
                <li class="page-item active"><a href="#" class="page-link">1</a></li>
                <li class="page-item"><a href="#" class="page-link">Next</a></li>
            </ul>
        </div>
    </div>
</div>
</div>     

app/views/users/login.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<title>Bootstrap Elegant Sign Up Form with Icons</title>
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:400,700">
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
<script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>
<style>
body {
  color: #999;
  background: #f5f5f5;
  font-family: 'Roboto', sans-serif;
}
.form-control, .form-control:focus, .input-group-addon {
  border-color: #e1e1e1;
  border-radius: 0;
}
.signup-form {
  width: 390px;
  margin: 0 auto;
  padding: 30px 0;
}
.signup-form h2 {
  color: #18A8D8;
  margin: 0 0 15px;
  text-align: center;
}
.signup-form .lead {
  font-size: 14px;
  margin-bottom: 30px;
  text-align: center;
}
.signup-form form {   
  border-radius: 1px;
  margin-bottom: 15px;
  background: #fff;
  border: 1px solid #f3f3f3;
  box-shadow: 0px 2px 2px rgba(0, 0, 0, 0.3);
  padding: 30px;
}
.signup-form .form-group {
  margin-bottom: 20px;
}
.signup-form label {
  font-weight: normal;
  font-size: 13px;
}
.signup-form .form-control {
  min-height: 38px;
  box-shadow: none !important;
  border-width: 0 0 1px 0;
} 
.signup-form .input-group-addon {
  max-width: 42px;
  text-align: center;
  background: none;
  border-bottom: 1px solid #e1e1e1;
  padding-left: 5px;
}
.signup-form .btn, .signup-form .btn:active {        
  font-size: 16px;
  font-weight: bold;
  background: #18A8D8 !important;
  border-radius: 3px;
  border: none;
  min-width: 140px;
}
.signup-form .btn:hover, .signup-form .btn:focus {
  background: #18A8D8 !important;
}
.signup-form a {
  color: #18A8D8;
  text-decoration: none;
} 
.signup-form a:hover {
  text-decoration: underline;
}
.signup-form .fa {
  font-size: 21px;
  position: relative;
  top: 8px;
}
.signup-form .fa-paper-plane {
  font-size: 17px;
}
.signup-form .fa-check {
  color: #fff;
  left: 9px;
  top: 18px;
  font-size: 7px;
  position: absolute;
}
</style>
</head>
<body>


<div class="signup-form"> 
    <% if flash[:notice] %>  
        <div class="alert alert-success"><%= flash[:notice] %></div>  
    <% end %>     

    <h2>COLLABORATE</h2>
    <p class="lead">a project management tool for developers.</p>



<form class="new_user" id="new_user" action="/devise/sign_in" accept-charset="UTF-8" method="post"><input type="hidden" name="authenticity_token" value="8m5Zz5u2lf1lfeHdgCU529qS2l9O2qKr3vdQuWsWV2IhUTBvA-PLF8uFNiWbEahmzqCpBV0buFKo7gyXrWC_6Q" autocomplete="off" />

    <%= form_with scope: @user, url: user_session_path, method: :post, local: true do %>
    <div class="form-group">
      <div class="input-group">
        <span class="input-group-addon"><i class="fa fa-paper-plane"></i></span>
        <%# <input type="email" class="form-control" name="email" placeholder="Email Address" required="required"> %>
        <input type="email" class="form-control" name="user[email]" id="user_email"  placeholder="Email Address" required="required">
        <%# <input autofocus="autofocus" autocomplete="email" type="email" value="" name="user[email]" id="user_email" /> %>
      </div>
    </div>
    <div class="form-group">
      <div class="input-group">
        <span class="input-group-addon"><i class="fa fa-lock"></i></span>
        <%# <input type="text" class="form-control" name="password" placeholder="Password" required="required"> %>
        <input type="password" class="form-control" name="user[password]" id="user_password" placeholder="Password" required="required">
        <%# <input autocomplete="current-password" type="password" name="user[password]" id="user_password" /> %>
      </div>
    </div>
         
    <div class="form-group">
            <button type="submit" name="commit" value="Log in" data-disable-with="Log in" class="btn btn-primary btn-block btn-lg">Sign in </button>
    </div>


  </div>

</form>



    <p class="small text-center">By clicking the Sign Up button, you agree to our <br><a href="#">Terms &amp; Conditions</a>, and <a href="#">Privacy Policy</a>.</p>
    <% end %> </form>
  <div class="text-center">Dont have an account? <%= link_to "Sign up", new_user_path %> here .</div>


</div>
</body>
</html>

app/views/users/new.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<title>My basecamp 1</title>
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:400,700">
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
<script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>
<style>
body {
  color: #999;
  background: #f5f5f5;
  font-family: 'Roboto', sans-serif;
}
.form-control, .form-control:focus, .input-group-addon {
  border-color: #e1e1e1;
  border-radius: 0;
}
.signup-form {
  width: 390px;
  margin: 0 auto;
  padding: 30px 0;
}
.signup-form h2 {
  color: #636363;
  margin: 0 0 15px;
  text-align: center;
}
.signup-form .lead {
  font-size: 14px;
  margin-bottom: 30px;
  text-align: center;
}
.signup-form form {   
  border-radius: 1px;
  margin-bottom: 15px;
  background: #fff;
  border: 1px solid #f3f3f3;
  box-shadow: 0px 2px 2px rgba(0, 0, 0, 0.3);
  padding: 30px;
}
.signup-form .form-group {
  margin-bottom: 20px;
}
.signup-form label {
  font-weight: normal;
  font-size: 13px;
}
.signup-form .form-control {
  min-height: 38px;
  box-shadow: none !important;
  border-width: 0 0 1px 0;
} 
.signup-form .input-group-addon {
  max-width: 42px;
  text-align: center;
  background: none;
  border-bottom: 1px solid #e1e1e1;
  padding-left: 5px;
}
.signup-form .btn, .signup-form .btn:active {        
  font-size: 16px;
  font-weight: bold;
  background: #18A8D8 !important;
  border-radius: 3px;
  border: none;
  min-width: 140px;
}
.signup-form .btn:hover, .signup-form .btn:focus {
  background: #18A8D8 !important;
}
.signup-form a {
  color: #18A8D8;
  text-decoration: none;
} 
.signup-form a:hover {
  text-decoration: underline;
}
.signup-form .fa {
  font-size: 21px;
  position: relative;
  top: 8px;
}
.signup-form .fa-paper-plane {
  font-size: 17px;
}
.signup-form .fa-check {
  color: #fff;
  left: 9px;
  top: 18px;
  font-size: 7px;
  position: absolute;
}
</style>
</head>
<body>
<div class="signup-form " style="text-align: center;"> 

  <img src="../images/logo.png" class="img-fluid " alt="..." width="150" height="150">

    <% if flash[:error] %>  
        <div class="alert alert-warning"><%= flash[:error] %></div>  
    <% end %>

    <h3>Sign Up</h3>
    
    <%= form_with scope: @user, url: users_path, method: :post, local: true do %>
      <div class="form-group">
        <div class="input-group">
          <span class="input-group-addon"><i class="fa fa-user"></i></span>
          <input type="text" class="form-control" name="name" placeholder="Name" required="required">
        </div>
      </div>
      <div class="form-group">
        <div class="input-group">
          <span class="input-group-addon"><i class="fa fa-paper-plane"></i></span>
          <input type="email" class="form-control" name="email" placeholder="Email Address" required="required">
        </div>
      </div>
    <div class="form-group">
      <div class="input-group">
        <span class="input-group-addon"><i class="fa fa-lock"></i></span>
        <input type="password" class="form-control" name="password" placeholder="Password" required="required">
      </div>
    </div>
    <div class="form-group">
      <div class="input-group">
        <span class="input-group-addon">
          <i class="fa fa-lock"></i>
          <i class="fa fa-check"></i>
        </span>
        <input type="password" class="form-control" name="confirm_password" placeholder="Confirm Password" required="required">
      </div>
    </div>        
    <div class="form-group">
            <button type="submit" class="btn btn-primary btn-block btn-lg">Sign Up</button>
    </div>
    <% end %>
    <p class="small text-center">By clicking the Sign Up button, you agree to our <br><a href="#">Terms &amp; Conditions</a>, and <a href="#">Privacy Policy</a>.</p>
    </form>
  <div class="text-center">Already have an account? <%= link_to "Login", users_login_path %> here .</div>
</div>
</body>
</html>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>
<%= @user.name %>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>