config/routes.rb
Rails.application.routes.draw do
  root 'application#index'
  get 'users/login', to: 'users#login'



  # TETING Process... ***************
  get 'home/show'
  get 'home/profile_page'

  # devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations' }
  # ***************

  # get 'users/login', to: 'projects#created'
 
  
  devise_for :users,
         path: 'devise'
        #path: 'project'


  devise_scope :user do
    get 'devise/sign_out', to: 'devise/sessions#destroy'
    get 'destroy_user/:id' => "users#destroy_user"
    get 'remove_from_admin/:id' => "users#remove_from_admin"
    get 'add_admin/:id' => "users#add_admin", as: 'add_admin_form'
    post 'add_admin/:id' => "users#add_admin", as: 'add_admin'
    # get 'sign_out', to: 'devise/sessions#destroy'
    get 'destroy_user/:id' => "users/sessions#destroy_user"
  

    # New ****************
    get 'user_admin', to: 'users/sessions#admin'
    delete 'destroy', to: 'users/sessions#destroy'
    get 'destroy_user/:id' => "users/sessions#destroy_user"
    get 'remove_from_admin/:id' => "users/sessions#remove_from_admin"
    get 'add_admin/:id' => "users/sessions#add_admin"

    get 'edit_user/:id' => "users#edit", as: 'edit_user_role'

      #******************


  end

  delete 'users/:id', to: 'users#destroy', as: 'delete_user'
  
  get 'users/add', to: 'users#adduser', as: 'add_user'
  post 'users/add', to: 'users#add_user', as: 'add_new_user'
  get 'projects/shared', to: 'projects#shared', as: 'shared_projects'
  get 'projects/created', to: 'projects#created', as: 'created_projects'
  post 'projects/new', to: 'projects#create', as: 'add_new_project'
  delete 'projects/:id', to: 'projects#destroy', as: 'destroy_project'
  get 'users', to: 'users#index', as: 'user_index'

  resources :projects
  resources :users
  
end

app/models/project.rb
class Project < ApplicationRecord
    #belog to relationship
    belongs_to :user

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

      # belongs_to :user
      before_action :authenticate_user!

      # GET method to get all projects from database   
      def index   
          @projects = current_user.projects
          #@project = current_user.projects.create(project_params)
          # @project = current_user.projects.create(project_params)
        #  @projects = Project.all 
                
      end   
       
      # GET method to get a project by id   
      def show   
        @project = Project.find(params[:id])  
        render :action => 'show' 
      end   
       
      # GET method for the new project form   
      def new   
        @project = Project.new   
      end   
       
      # POST method for processing form data   
     # @projects = current_user.projects


      def create  
      
        @project = Project.new(project_params)
        @project.user = current_user
        @project.save
        redirect_to projects_path


        # @project = Project.new(project_params)   
        # if @project.save   
        #   flash[:notice] = 'project added!'   
        #   redirect_to new_project_url  
        # else   
        #   flash[:error] = 'Failed to edit project!'   
        #   render :new   
        # end   
      end   
       
       # GET method for editing a project based on id   
      def edit   
        @project = Project.find(params[:id]) 
        render :edit  
      end   
       
      # PUT method for updating in database a project based on id   
      def update   
        @project = Project.find(params[:id])   
        if @project.update(project_params)   
          flash[:notice] = 'project updated successfully!'   
          redirect_to edit_project_path(@project.id)
        else   
          flash[:error] = 'Failed to edit project!'   
          render :edit   
        end   
      end   
       
      # DELETE method for deleting a project from database based on id   
      def destroy  
        # @project = Project.find(params[:id])

        # if current_user == @project.user || current_user.admin == true
        #   @project.destroy
        #   redirect_to projects_path, notice: "Project deleted successfully"
        # else
        #   redirect_to project_url, alert: "You are not authorized to delete this project"
        # end
        
        

        
        project = Project.find(params[:id])   
        # if project.destroy   
        if @project.destroy(project_params)
          flash[:notice] = 'project deleted!'   
          redirect_to projects_path   
        else   
          flash[:error] = 'Failed to delete this project!'   
          render :destroy   
        end   
      end     
      
      def shared
        @projects = Project.all  
      end

      def created
        @projects = Project.all  
      end

      protected

      # validation of params   
      def project_params   
        params.permit(:name, :description)   
      end   


      #new controls
      def show
        @users = User.all
      end

      def profile_page
        @user = current_user
      end
      #*******************
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/created.html.erb
<div class="container-xl">
    <div class="table-responsive">
        <div class="table-wrapper">
            <div class="table-title">
                <div class="row">
                    <div class="col-sm-5">
                        <h2><b>All Projects</b></h2>
                    </div>
                    <div class="col-sm-7">
                        <a href="<%= new_project_path %>" class="btn btn-secondary"><i class="material-icons">&#xE147;</i> <span>Add New Project</span></a>
                    </div>
                </div>
            </div>
            <table class="table table-striped table-hover">
                <thead>
                    <tr>
                        <th>#</th>
                        <th>Name</th>                       
                        <th>Description</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                <% @projects.each_with_index do |project, k| %>
                    <tr>
                        <td> <%= k+1 %>  </td>
                        <td> <%= project.name %> </td>
                        <td> <%= project.description %> </td>                        
                        <td style="width: 140px">
                            <a href="#" class="edit" title="Edit" data-toggle="tooltip"><i class="material-icons">&#xE254;</i></a>
                            <a href="#" class="delete" title="Delete" data-toggle="tooltip"><i class="material-icons">&#xE872;</i></a>
                        </td>
                    </tr>  
                    <% end %>                  
                </tbody>
            </table>
            <div class="clearfix">
                <div class="hint-text">No. of entries</div>
                <ul class="pagination">
                    <li class="page-item disabled"><a href="#">Previous</a></li>
                    <li class="page-item active"><a href="#" class="page-link">1</a></li>
                    <li class="page-item"><a href="#" class="page-link">Next</a></li>
                </ul>
            </div>
        </div>
    </div>
</div>     

app/views/projects/edit.html.erb
<div class="container-xl">
    <div class="table-responsive">
        <div class="table-wrapper">
            <div class="table-title">
                <div class="row">
                    <div class="col-sm-5">
                        <h2> <b>New Project </b></h2>
                    </div>                    
                </div>
            </div>
            <div class="signup-form"> 
            <% if flash[:notice] %>  
            <div class="alert alert-success"><%= flash[:notice] %></div>  
                <% end %> 

                <% if flash[:error] %>  
                <div class="alert alert-warning"><%= flash[:error] %></div>  
                <% end %>  

            <%= form_with scope: @project, url: project_path, method: :patch, local: true do %>
            <h2>COLLABORATE</h2>
            <p class="lead">create a new project management tool for developers.</p>
            
                <div class="form-group">
            <div class="input-group">
                <input type="text" class="form-control" name="name" placeholder="Project Name" value="<%= @project.name %>" required="required">
            </div>
                </div>
            <div class="form-group">
            <div class="input-group">
            <textarea class="form-control" name="description" placeholder="Project Description" rows="5"><%= @project.description %> </textarea>   
            </div>
                </div>
                
            <div class="form-group">
                    <button type="submit" class="btn btn-primary btn-block btn-lg">Update</button>
            </div>
             <% end %>         
            
    </div>
</div>     

app/views/projects/index.html.erb
<div class="container-xl">
    <div class="table-responsive">
        <div class="table-wrapper">
            <div class="table-title">
                <div class="row">
                    <div class="col-sm-5">
                        <h2> <b>My Projects </b></h2>
                    </div>
                    <div class="col-sm-7">
                        <a href="<%= new_project_path %>" class="btn btn-secondary"><i class="material-icons">&#xE147;</i> <span>Add New Project</span></a>
                    </div>
                    
                </div>
            </div>
            <table class="table table-striped table-hover">
                <thead>
                    <tr>
                        <th><b>#</b></th>
                        <th><b>Name of Projects</b></th>                       
                        <th><b>Description</b></th>
                        <th><b>Action</b></th>
                    </tr>
                </thead>
                <tbody>
                <% @projects.each_with_index do |project, k| %>
                    <tr>
                        <td> <%= k+1 %>  </td>
                        <td> <%= project.name %> </td>
                        <td> <%= project.description %> </td>                        
                        <td style="width: 100px">
                            <%= link_to "Edit", edit_project_path(:id => project.id), method: 'get' %> 
                       
                          <%= link_to "Delete", destroy_project_path(:id => project.id), method: 'delete' %>  
                           
                            <%# <%= link_to "Delete", destroy_project_path(project), method: 'delete' %> 
                            
                        </td>
                    </tr>  
                    <% end %>                  
                </tbody>
            </table>
            <div class="clearfix">
                <div class="hint-text">No. of entries</div>
                <ul class="pagination">
                    <li class="page-item disabled"><a href="#">Previous</a></li>
                    <li class="page-item active"><a href="#" class="page-link">1</a></li>
                    <li class="page-item"><a href="#" class="page-link">Next</a></li>
                </ul>
            </div>
        </div>
    </div>
</div>     

app/views/projects/new.html.erb
<div class="container-xl">
    <div class="table-responsive">
        <div class="table-wrapper">
            <div class="table-title">
                <div class="row">
                    <div class="col-sm-5">
                        <h2> <b>New Project </b></h2>
                    </div>                    
                </div>
            </div>
            <div class="signup-form"> 
            <% if flash[:notice] %>  
            <div class="alert alert-success"><%= flash[:notice] %></div>  
                <% end %> 

                <% if flash[:error] %>  
                <div class="alert alert-warning"><%= flash[:error] %></div>  
                <% end %>  

            <%= form_with scope: @project, url: add_new_project_path, method: :post, local: true do %>
            <h2>COLLABORATE</h2>
            <p class="lead">create a new project management tool for developers.</p>
            
                <div class="form-group">
            <div class="input-group">
                <input type="text" class="form-control" name="name" placeholder="Project Name" required="required">
            </div>
                </div>
            <div class="form-group">
            <div class="input-group">
            <textarea class="form-control" name="description" placeholder="Project Description" rows="5"></textarea>   
            </div>
                </div>
                
            <div class="form-group">
                    <button type="submit" class="btn btn-primary btn-block btn-lg">Create</button>
            </div>
             <% end %>         
            
    </div>
</div>     

app/views/projects/shared.html.erb
<div class="container-xl">
    <div class="table-responsive">
        <div class="table-wrapper">
            <div class="table-title">
                <div class="row">
                    <div class="col-sm-5">
                        <h2><b>Shared Projects </b></h2>
                    </div>
                    <div class="col-sm-7">
                        <a href="<%= new_project_path %>" class="btn btn-secondary"><i class="material-icons">&#xE147;</i> <span>Add New Project</span></a>
                    </div>
                </div>
            </div>
            <table class="table table-striped table-hover">
                <thead>
                    <tr>
                        <th>#</th>
                        <th>Name</th>                       
                        <th>Description</th>
                        <th>Created by</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>1</td>
                        <td><a href="#"> Martins Ake</a></td>
                        <td>01/2/2023</td>                        
                        <td>Admin</td>

                    <td style="width: 140px">
                            <%# <a href="#" class="view" title="View" data-toggle="tooltip"><i class="material-icons">&#xE417;</i></a> %>
                            <a href="#" class="edit" title="Edit" data-toggle="tooltip"><i class="material-icons">&#xE254;</i></a>
                            <a href="#" class="delete" title="Delete" data-toggle="tooltip"><i class="material-icons">&#xE872;</i></a>
                        </td>

                    <tr>
                        <td>2</td>
                        <td><a href="#"> Mohammed Awwal</a></td>
                        <td>6/2/2023</td>                        
                        <td>User</td>

                        <td style="width: 140px">
                            <%# <a href="#" class="view" title="View" data-toggle="tooltip"><i class="material-icons">&#xE417;</i></a> %>
                            <a href="#" class="edit" title="Edit" data-toggle="tooltip"><i class="material-icons">&#xE254;</i></a>
                            <a href="#" class="delete" title="Delete" data-toggle="tooltip"><i class="material-icons">&#xE872;</i></a>
                        </td>

                    </tr>

                    <tr>
                        <td>3</td>
                        <td><a href="#"> Deborah Andy</a></td>
                        <td>04/3/2032</td>                        
                        <td>Admin</td>

                        <td style="width: 140px">
                            <%# <a href="#" class="view" title="View" data-toggle="tooltip"><i class="material-icons">&#xE417;</i></a> %>
                            <a href="#" class="edit" title="Edit" data-toggle="tooltip"><i class="material-icons">&#xE254;</i></a>
                            <a href="#" class="delete" title="Delete" data-toggle="tooltip"><i class="material-icons">&#xE872;</i></a>
                        </td>

                    </tr>

                    </tr>                    
                </tbody>
            </table>



            <div class="clearfix">
                <div class="hint-text">Showing <b>5</b> out of <b>25</b> entries</div>
                <ul class="pagination">
                    <li class="page-item disabled"><a href="#">Previous</a></li>
                    <li class="page-item active"><a href="#" class="page-link">1</a></li>
                    <li class="page-item"><a href="#" class="page-link">Next</a></li>
                </ul>
            </div>
        </div>
    </div>
</div>     

app/views/projects/show.html.erb
<div class="container-xl">
    <div class="table-responsive">
        <div class="table-wrapper">
            <div class="table-title">
                <div class="row">
                    <div class="col-sm-5">
                        <h2> <b>Edit Project </b></h2>
                    </div>  
                      
                <div class="col-sm-7">
                        <a href="#" class="btn btn-secondary" data-toggle="modal" data-target="#exampleModalCenter"><i class="material-icons">&#xE147;</i> <span>Manage Members</span></a>
                </div>
            </div>

            </div>
            <div class="signup-form"> 
            <form action="" method="post">
            <h2>COLLABORATE</h2>
            <p class="lead">Edit project and add members to the project</p>
            
                <div class="form-group">
            <div class="input-group">
                <input type="text" class="form-control" name="name" placeholder="Project Name" required="required">
            </div>
                </div>
            <div class="form-group">
                <div class="input-group">
                <textarea class="form-control" id="description" placeholder="Project Description" rows="5"></textarea>   
                </div>
            </div>
                
            <div class="form-group">
                    <button type="submit" class="btn btn-primary btn-block btn-lg">Update</button>
            </div>
            </form>   
    </div>
</div>     


<!-- Modal section  -->
<div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalCenterTitle">Member Manager</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">


    <div class="input-group mb-3">
    <input type="text" class="form-control" placeholder="member valid email" aria-label="Recipient's username" aria-describedby="button-addon2">
    <div class="input-group-append">
    <button class="btn btn-outline-secondary" type="button" id="button-addon2">Add</button>
    </div>
    </div>
        ...
      </div>
      <div class="modal-footer">
      <table class="table table-striped table-hover">
      <thead>
          <tr>
              <th>#</th>
              <th>Member Name</th>                       
              <th>Email</th>
              <th>Action</th>
          </tr>
      </thead>
      <tbody>
          <tr>
              <td>1</td>
              <td><a href="#"><img src="/examples/images/avatar/1.jpg" class="avatar" alt="Avatar"> Michael Holz</a></td>                       
              <td>Admin</td>
              <td>
                  <a href="#" class="delete" title="Delete" data-toggle="tooltip"><i class="material-icons">&#xE872;</i></a>
              </td>
          </tr>                    
      </tbody>
  </table>
      </div>
    </div>
  </div>
</div>
<!-- end of modal  --> 

app/views/projects/update.html.erb
<h1>Projects#update</h1>
<p>Find me in app/views/projects/update.html.erb</p>