config/routes.rb
Rails.application.routes.draw do
  root 'application#index'
  get 'users/login', to: 'users#login'



  # TETING Process... ***************
  get 'home/show'
  get 'home/profile_page'

  # devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations' }
  # ***************

  # get 'users/login', to: 'projects#created'
 
  
  devise_for :users,
         path: 'devise'
        #path: 'project'


  devise_scope :user do
    get 'devise/sign_out', to: 'devise/sessions#destroy'
    get 'destroy_user/:id' => "users#destroy_user"
    get 'remove_from_admin/:id' => "users#remove_from_admin"
    get 'add_admin/:id' => "users#add_admin", as: 'add_admin_form'
    post 'add_admin/:id' => "users#add_admin", as: 'add_admin'
    # get 'sign_out', to: 'devise/sessions#destroy'
    get 'destroy_user/:id' => "users/sessions#destroy_user"
  

    # New ****************
    get 'user_admin', to: 'users/sessions#admin'
    delete 'destroy', to: 'users/sessions#destroy'
    get 'destroy_user/:id' => "users/sessions#destroy_user"
    get 'remove_from_admin/:id' => "users/sessions#remove_from_admin"
    get 'add_admin/:id' => "users/sessions#add_admin"

    get 'edit_user/:id' => "users#edit", as: 'edit_user_role'

      #******************


  end

  delete 'users/:id', to: 'users#destroy', as: 'delete_user'
  
  get 'users/add', to: 'users#adduser', as: 'add_user'
  post 'users/add', to: 'users#add_user', as: 'add_new_user'
  get 'projects/shared', to: 'projects#shared', as: 'shared_projects'
  get 'projects/created', to: 'projects#created', as: 'created_projects'
  post 'projects/new', to: 'projects#create', as: 'add_new_project'
  delete 'projects/:id', to: 'projects#destroy', as: 'destroy_project'
  get 'users', to: 'users#index', as: 'user_index'

  resources :projects
  resources :users
  
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyBasecamp1</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Merienda+One">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>
    <style>
    body {
        background: #eeeeee;
    }
    .form-inline {
        display: inline-block;
    }
    .navbar-header.col {
        padding: 0 !important;
    }
    .navbar {       
        background: #fff;
        padding-left: 16px;
        padding-right: 16px;
        border-bottom: 1px solid #d6d6d6;
        box-shadow: 0 0 4px rgba(0,0,0,.1);
    }
    .nav-link img {
        border-radius: 50%;
        width: 36px;
        height: 36px;
        margin: -8px 0;
        float: left;
        margin-right: 10px;
    }
    .navbar .navbar-brand {
        color: #555;
        padding-left: 0;
        padding-right: 50px;
        font-family: 'Merienda One', sans-serif;
    }
    .navbar .navbar-brand i {
        font-size: 20px;
        margin-right: 5px;
    }
    .search-box {
        position: relative;
    }   
    .search-box input {
        box-shadow: none;
        padding-right: 35px;
        border-radius: 3px !important;
    }
    .search-box .input-group-addon {
        min-width: 35px;
        border: none;
        background: transparent;
        position: absolute;
        right: 0;
        z-index: 9;
        padding: 7px;
        height: 100%;
    }
    .search-box i {
        color: #a0a5b1;
        font-size: 19px;
    }
    .navbar .nav-item i {
        font-size: 18px;
    }
    .navbar .dropdown-item i {
        font-size: 16px;
        min-width: 22px;
    }
    .navbar .nav-item.open > a {
        background: none !important;
    }
    .navbar .dropdown-menu {
        border-radius: 1px;
        border-color: #e5e5e5;
        box-shadow: 0 2px 8px rgba(0,0,0,.05);
    }
    .navbar .dropdown-menu a {
        color: #777;
        padding: 8px 20px;
        line-height: normal;
    }
    .navbar .dropdown-menu a:hover, .navbar .dropdown-menu a:active {
        color: #333;
    }   
    .navbar .dropdown-item .material-icons {
        font-size: 21px;
        line-height: 16px;
        vertical-align: middle;
        margin-top: -2px;
    }
    .navbar .badge {
        color: #fff;
        background: #f44336;
        font-size: 11px;
        border-radius: 20px;
        position: absolute;
        min-width: 10px;
        padding: 4px 6px 0;
        min-height: 18px;
        top: 5px;
    }
    .navbar a.notifications, .navbar a.messages {
        position: relative;
        margin-right: 10px;
    }
    .navbar a.messages {
        margin-right: 20px;
    }
    .navbar a.notifications .badge {
        margin-left: -8px;
    }
    .navbar a.messages .badge {
        margin-left: -4px;
    }   
    .navbar .active a, .navbar .active a:hover, .navbar .active a:focus {
        background: transparent !important;
    }
    @media (min-width: 1200px){
        .form-inline .input-group {
            width: 300px;
            margin-left: 30px;
        }
    }
    @media (max-width: 1199px){
        .form-inline {
            display: block;
            margin-bottom: 10px;
        }
        .input-group {
            width: 100%;
        }
    }
    </style>

    <style>
    body {
        color: #566787;
        background: #f5f5f5;
        font-family: 'Varela Round', sans-serif;
        font-size: 13px;
    }
    .table-responsive {
        margin: 30px 0;
    }
    .table-wrapper {
        min-width: 1000px;
        background: #fff;
        padding: 20px 25px;
        border-radius: 3px;
        box-shadow: 0 1px 1px rgba(0,0,0,.05);
    }
    .table-title {
        padding-bottom: 15px;
        background: #299be4;
        color: #fff;
        padding: 16px 30px;
        margin: -20px -25px 10px;
        border-radius: 3px 3px 0 0;
    }
    .table-title h2 {
        margin: 5px 0 0;
        font-size: 24px;
    }
    .table-title .btn {
        color: #566787;
        float: right;
        font-size: 13px;
        background: #fff;
        border: none;
        min-width: 50px;
        border-radius: 2px;
        border: none;
        outline: none !important;
        margin-left: 10px;
    }
    .table-title .btn:hover, .table-title .btn:focus {
        color: #566787;
        background: #f2f2f2;
    }
    .table-title .btn i {
        float: left;
        font-size: 21px;
        margin-right: 5px;
    }
    .table-title .btn span {
        float: left;
        margin-top: 2px;
    }
    table.table tr th, table.table tr td {
        border-color: #e9e9e9;
        padding: 12px 15px;
        vertical-align: middle;
    }
    table.table tr th:first-child {
        width: 60px;
    }
    table.table tr th:last-child {
        width: 100px;
    }
    table.table-striped tbody tr:nth-of-type(odd) {
        background-color: #fcfcfc;
    }
    table.table-striped.table-hover tbody tr:hover {
        background: #f5f5f5;
    }
    table.table th i {
        font-size: 13px;
        margin: 0 5px;
        cursor: pointer;
    }   
    table.table td:last-child i {
        opacity: 0.9;
        font-size: 22px;
        margin: 0 5px;
    }
    table.table td a {
        font-weight: bold;
        color: #566787;
        display: inline-block;
        text-decoration: none;
    }
    table.table td a:hover {
        color: #2196F3;
    }
    table.table td a.settings {
        color: #2196F3;
    }
    table.table td a.delete {
        color: #F44336;
    }
    table.table td i {
        font-size: 19px;
    }
    table.table .avatar {
        border-radius: 50%;
        vertical-align: middle;
        margin-right: 10px;
    }
    .status {
        font-size: 30px;
        margin: 2px 2px 0 0;
        display: inline-block;
        vertical-align: middle;
        line-height: 10px;
    }
    .text-success {
        color: #10c469;
    }
    .text-info {
        color: #62c9e8;
    }
    .text-warning {
        color: #FFC107;
    }
    .text-danger {
        color: #ff5b5b;
    }
    .pagination {
        float: right;
        margin: 0 0 5px;
    }
    .pagination li a {
        border: none;
        font-size: 13px;
        min-width: 30px;
        min-height: 30px;
        color: #999;
        margin: 0 2px;
        line-height: 30px;
        border-radius: 2px !important;
        text-align: center;
        padding: 0 6px;
    }
    .pagination li a:hover {
        color: #666;
    }   
    .pagination li.active a, .pagination li.active a.page-link {
        background: #03A9F4;
    }
    .pagination li.active a:hover {        
        background: #0397d6;
    }
    .pagination li.disabled i {
        color: #ccc;
    }
    .pagination li i {
        font-size: 16px;
        padding-top: 6px
    }
    .hint-text {
        float: left;
        margin-top: 10px;
        font-size: 13px;
    }
    </style>
    <script>
    $(document).ready(function(){
        $('[data-toggle="tooltip"]').tooltip();
    });
    </script>

</head> 
<body>
<% if current_user %>
<nav class="navbar navbar-expand-xl navbar-light bg-light">
    <a href="#" class="navbar-brand"><i class="fa fa-cube"></i>My Basecamp<b>1</b></a>
    <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
        <span class="navbar-toggler-icon"></span>
    </button>
    <!-- Collection of nav links, forms, and other content for toggling -->
    <div id="navbarCollapse" class="collapse navbar-collapse justify-content-start">
        <div class="navbar-nav">
            <%= link_to 'Dashboard', projects_path, class: 'nav-item nav-link'%>
            <div class="nav-item dropdown">
                <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown">Projects</a>
                <div class="dropdown-menu">
                    <%= link_to 'My Projects', projects_path, class: 'dropdown-item'%>
                    <%= link_to 'All projects', created_projects_path, class: 'dropdown-item'%>
                    <%= link_to 'Shared projects', shared_projects_path, class: 'dropdown-item'%>
                </div>
            </div>


            <% if current_user.admin? %>
            <div class="nav-item dropdown">
                <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown">Users</a>
                <div class="dropdown-menu">
                    <%= link_to 'Add User', add_user_path, class: 'dropdown-item'%>
                    <%= link_to 'Manage Users', users_path, class: 'dropdown-item'%>
                </div>
            </div>
            <% end %>

        </div>
        <div style="float:right">
            <%= link_to(destroy_user_session_path, {:class => "nav-link", :method => :delete}) do  %>
                <span class="sidebar-normal"> Logout </span>
            <% end %>
        </div>
        
        <!-- <div class="navbar-nav ml-auto">
            <div class="nav-item dropdown">
               <div class="dropdown-menu">
                    <a href="#" class="dropdown-item"><i class="fa fa-user-o"></i> Profile</a></a>
                    <a href="#" class="dropdown-item"><i class="fa fa-sliders"></i> Settings</a></a>
                    <div class="dropdown-divider"></div>
                    <a href="#" class="dropdown-item"><i class="material-icons">&#xE8AC;</i> Logout</a>
                </div>
            </div>
        -->
        </div>
    </div>
</nav>

<% end %>
<body>
 
  <%=yield %>
  
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
  
</body>
</html>